LENGTH_HINT = "아직도 못 맞추셨어요? 단어의 길이는 {answer}입니다."
FIRST_CHARACTER_HINT = "힌트 드릴게요.. 첫 번째 글자는 {answer[0]}입니다."
FAILED_MESSAGE = "안타깝네요.. 정답은 {answer[0]} 였습니다."
EXIT_MESSAGE = "Bye~~"
TRY_AGAIN_MESSAGE = "다시 생각해~"
CORRECT_MESSAGE = "정답! {count}문제 남았습니다!"
END_MESSAGE = "끝!!"
